#!/usr/bin/env bash

# version
VERSION="0.4.2-noqqe"

# bookmarks file
BOOKMARKS=~/.bookmarks

# Output usage info
#

usage() {
  cat <<EOF

  Usage: bm [cmd]

  Commands:

    # add a bookmark with the given url and optional tags
    $ bm add <url> [tag...]

    # list bookmarks available
    $ bm list|ls
    $ bm
    $ bm 20

    # open the first bookmark matching <query>
    $ bm open <query>

    # search the bookmarks via full-text <query>
    $ bm search <query>

    # list tags
    $ bm tags

    # display statistics about the bookmarks
    $ bm statistics
    $ bm stats

    # show help information
    $ bm help|-h|--help

    # show version information
    $ bm version|-V|--version

EOF
}


# Add a bookmark
#   <url> [tag ...]
save_bookmark() {
  local url=$1
  local tags=${@:2}
  local date=$(date +%FT%H:%M:%S%z)
  local title=$(curl -L "$url" -so -| grep -iPo '(?<=<title>)(.*)(?=</title>)'| sed 's#|# #g')
  echo "  Added bookmark"
  echo "    title: $title"
  echo "    url: $url"
  echo "    tags: $tags"
  echo "    date: $date"
  echo "$url|$tags|$date|$title" >> $BOOKMARKS
}


# List all bookmarks
#
list_bookmarks() {
  echo
  cat $BOOKMARKS | tail -${1:-10} \
    | awk '
    BEGIN { FS = "|" }
    {
      printf "* title: \033[1;32m%s\033[0m\n", $4
      printf "  url: %s\n", $1
      printf "  tags: \033[1;37m%s\033[0m\n", $2
      printf "  date: %s\n\n", $3
    }'
}


# Search all bookmarks with <query>
# <query>
search_bookmarks() {
  echo "Results for $1:"
  echo
  cat $BOOKMARKS \
    | grep -i $1 \
    | awk '
    BEGIN { FS = "|" }
    {
      printf "* title: \033[1;32m%s\033[0m\n", $4
      printf "  url: %s\n", $1
      printf "  tags: \033[1;37m%s\033[0m\n", $2
      printf "  date: %s\n\n", $3
    }'
}


# Open first bookmark matching <query>
# <query>
open_bookmark() {
  cat $BOOKMARKS \
    | grep $1 \
    | cut -d '|' -f 1 \
    | xargs open
}


# Diplay some statistics about the bookmarks
#
show_statistics() {
  local total_bookmarks=$(cat $BOOKMARKS | wc -l | sed 's/^ *//')
  local total_tags=$(list_tags | wc -l | sed 's/^ *//')
  echo "    total bookmarks: $total_bookmarks"
  echo "         total tags: $total_tags"
  echo "        top 10 tags: `display_top_ten_tags`"
}


# Output tags.
#
list_tags() {
  cat $BOOKMARKS \
    | cut -f2 -d '|' \
    | tr " " "\n" \
    | sort \
    | uniq -c \
    | sort -nr
}


# Display the 10 most frequently used tags
#
display_top_ten_tags() {
  echo
  printf "%20s  %s\n" count tag
  list_tags \
    | head -10 \
    | awk '{ printf("%20d  %s\n", $1, $2) }'
}


# List urls
# <query>
urls() {
  cat $BOOKMARKS \
    | grep "$1" \
    | cut -d '|' -f 1
}


# no args
if test $# -eq 0; then
  list_bookmarks 10
  exit
fi

# parse args
while test $# -ne 0; do
  arg=$1; shift
  case $arg in
    version|-V|--version) echo $VERSION; exit ;;
    help|-h|--help) usage; exit ;;
    tags) list_tags; exit ;;
    ls|list) list_bookmarks "$@"; exit ;;
    search) search_bookmarks "$@"; exit ;;
    open) open_bookmark "$@"; exit ;;
    add) save_bookmark "$@"; exit ;;
    stats|statistics) show_statistics; exit ;;
    *) list_bookmarks $arg; exit ;;
  esac
done
